-- ============================================================================
-- Seed baseline IAM data: privileges, roles, and role-privilege grants.
--
-- A root user is created at application startup (see IamBootstrap.java) so the
-- password hash is generated by the configured PasswordEncoder rather than
-- hard-coded here.
-- ============================================================================

INSERT INTO iam_privilege (name, description, created_at, updated_at, created_by, updated_by, version) VALUES
    -- IAM
    ('USER_READ',          'View users',                      NOW(), NOW(), 'system', 'system', 0),
    ('USER_CREATE',        'Create users',                    NOW(), NOW(), 'system', 'system', 0),
    ('USER_UPDATE',        'Update users (incl. role grants)',NOW(), NOW(), 'system', 'system', 0),
    ('USER_DELETE',        'Delete users',                    NOW(), NOW(), 'system', 'system', 0),
    ('ROLE_READ',          'View roles and privileges',       NOW(), NOW(), 'system', 'system', 0),
    ('ROLE_CREATE',        'Create roles',                    NOW(), NOW(), 'system', 'system', 0),
    ('ROLE_UPDATE',        'Update roles and their privileges',NOW(),NOW(), 'system', 'system', 0),
    ('ROLE_DELETE',        'Delete roles',                    NOW(), NOW(), 'system', 'system', 0),

    -- Module access flags (broad gates, used while module-specific privileges are added)
    ('PATIENT_ACCESS',     'Access the patient module',       NOW(), NOW(), 'system', 'system', 0),
    ('ENCOUNTER_ACCESS',   'Access the encounter module',     NOW(), NOW(), 'system', 'system', 0),
    ('ORDERS_ACCESS',      'Access the orders module',        NOW(), NOW(), 'system', 'system', 0),
    ('PHARMACY_ACCESS',    'Access the pharmacy module',      NOW(), NOW(), 'system', 'system', 0),
    ('PROCUREMENT_ACCESS', 'Access the procurement module',   NOW(), NOW(), 'system', 'system', 0),
    ('BILLING_ACCESS',     'Access the billing module',       NOW(), NOW(), 'system', 'system', 0),
    ('HR_ACCESS',          'Access the HR module',            NOW(), NOW(), 'system', 'system', 0),
    ('REPORTING_ACCESS',   'Access the reporting module',     NOW(), NOW(), 'system', 'system', 0),
    ('MASTERDATA_MANAGE',  'Manage master data catalogs',     NOW(), NOW(), 'system', 'system', 0);

INSERT INTO iam_role (name, description, created_at, updated_at, created_by, updated_by, version) VALUES
    ('ROOT',         'Super administrator (all privileges)',           NOW(), NOW(), 'system', 'system', 0),
    ('ADMIN',        'System administrator',                           NOW(), NOW(), 'system', 'system', 0),
    ('RECEPTION',    'Patient registration and reception',             NOW(), NOW(), 'system', 'system', 0),
    ('CLINICIAN',    'Doctor / clinical practitioner',                 NOW(), NOW(), 'system', 'system', 0),
    ('NURSE',        'Nursing staff',                                  NOW(), NOW(), 'system', 'system', 0),
    ('PHARMACIST',   'Pharmacy staff',                                 NOW(), NOW(), 'system', 'system', 0),
    ('LABORATORIST', 'Lab technician',                                 NOW(), NOW(), 'system', 'system', 0),
    ('RADIOGRAPHER', 'Radiology technician',                           NOW(), NOW(), 'system', 'system', 0),
    ('CASHIER',      'Cashier / billing clerk',                        NOW(), NOW(), 'system', 'system', 0),
    ('ACCOUNTANT',   'Accounting',                                     NOW(), NOW(), 'system', 'system', 0),
    ('HR',           'Human resources',                                NOW(), NOW(), 'system', 'system', 0),
    ('PROCUREMENT',  'Procurement and supplier management',            NOW(), NOW(), 'system', 'system', 0),
    ('STORE_PERSON', 'Inventory store keeper',                         NOW(), NOW(), 'system', 'system', 0),
    ('MANAGEMENT',   'Management dashboards and reports (read-only)',  NOW(), NOW(), 'system', 'system', 0);

-- Grant every privilege to ROOT
INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'ROOT'), p.id
FROM iam_privilege p;

-- Grant IAM management privileges to ADMIN
INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'ADMIN'), p.id
FROM iam_privilege p
WHERE p.name IN ('USER_READ','USER_CREATE','USER_UPDATE','USER_DELETE',
                 'ROLE_READ','ROLE_CREATE','ROLE_UPDATE','ROLE_DELETE',
                 'MASTERDATA_MANAGE');

-- Module access grants by role (broad gates; refine later as fine-grained
-- privileges are introduced per module).
INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'RECEPTION'), p.id
FROM iam_privilege p
WHERE p.name IN ('PATIENT_ACCESS','BILLING_ACCESS');

INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'CLINICIAN'), p.id
FROM iam_privilege p
WHERE p.name IN ('PATIENT_ACCESS','ENCOUNTER_ACCESS','ORDERS_ACCESS');

INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'NURSE'), p.id
FROM iam_privilege p
WHERE p.name IN ('PATIENT_ACCESS','ENCOUNTER_ACCESS','ORDERS_ACCESS');

INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'PHARMACIST'), p.id
FROM iam_privilege p
WHERE p.name IN ('PHARMACY_ACCESS','ORDERS_ACCESS');

INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'LABORATORIST'), p.id
FROM iam_privilege p
WHERE p.name IN ('ORDERS_ACCESS');

INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'RADIOGRAPHER'), p.id
FROM iam_privilege p
WHERE p.name IN ('ORDERS_ACCESS');

INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'CASHIER'), p.id
FROM iam_privilege p
WHERE p.name IN ('BILLING_ACCESS');

INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'ACCOUNTANT'), p.id
FROM iam_privilege p
WHERE p.name IN ('BILLING_ACCESS','REPORTING_ACCESS');

INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'HR'), p.id
FROM iam_privilege p
WHERE p.name IN ('HR_ACCESS');

INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'PROCUREMENT'), p.id
FROM iam_privilege p
WHERE p.name IN ('PROCUREMENT_ACCESS');

INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'STORE_PERSON'), p.id
FROM iam_privilege p
WHERE p.name IN ('PROCUREMENT_ACCESS','PHARMACY_ACCESS');

INSERT INTO iam_role_privilege (role_id, privilege_id)
SELECT (SELECT id FROM iam_role WHERE name = 'MANAGEMENT'), p.id
FROM iam_privilege p
WHERE p.name IN ('REPORTING_ACCESS','BILLING_ACCESS');
